import { Dimensions, StyleSheet } from 'react-native';
import { moderateScale, scale } from '../lib/scaling';
import { ThemeTokens } from './types';

const SCREEN_WIDTH = Dimensions.get('window').width;

export type AppStyles = ReturnType<typeof createStyles>;

export function createStyles(theme: ThemeTokens, insetsTop: number, insetsBottom: number) {
  return StyleSheet.create({
    app: { flex: 1, backgroundColor: theme.background },
    shell: {
      flex: 1,
      width: '100%',
      maxWidth: 680,
      alignSelf: 'center',
      backgroundColor: theme.background,
    },
    centerLoader: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      padding: scale(24),
    },
    loaderCard: {
      width: '100%',
      maxWidth: 360,
      padding: scale(22),
      borderRadius: scale(28),
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
      alignItems: 'center',
      shadowColor: theme.shadow,
      shadowOpacity: 0.22,
      shadowRadius: 24,
      shadowOffset: { width: 0, height: 12 },
      elevation: 4,
    },
    loaderTitle: {
      color: theme.text,
      marginTop: scale(14),
      fontSize: moderateScale(22),
      fontWeight: '900',
      letterSpacing: 0.4,
    },
    loaderSubtitle: {
      color: theme.muted,
      marginTop: scale(8),
      textAlign: 'center',
      fontSize: moderateScale(13),
      lineHeight: moderateScale(19),
    },
    header: {
      paddingTop: insetsTop + scale(8),
      paddingHorizontal: scale(16),
      paddingBottom: scale(10),
      backgroundColor: theme.background,
    },
    headerTop: { flexDirection: 'row', alignItems: 'center', gap: scale(10) },
    headerTitleWrap: { flex: 1, minWidth: 0 },
    appTitle: {
      color: theme.text,
      fontSize: moderateScale(20),
      fontWeight: '900',
      letterSpacing: 0.5,
    },
    appSubtitle: {
      color: theme.muted,
      marginTop: scale(1),
      marginBottom: scale(2),
      fontSize: moderateScale(13),
      lineHeight: moderateScale(18),
    },
    iconButton: {
      width: scale(42),
      height: scale(42),
      borderRadius: scale(14),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
    },
    profileBadge: {
      minWidth: scale(42),
      height: scale(42),
      paddingHorizontal: scale(12),
      borderRadius: scale(14),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.primary,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.14)',
    },
    profileBadgeText: { color: theme.primaryText, fontSize: moderateScale(14), fontWeight: '900' },
    heroCard: {
      marginTop: scale(14),
      padding: scale(16),
      borderRadius: scale(28),
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
      shadowColor: theme.shadow,
      shadowOpacity: 0.22,
      shadowRadius: 24,
      shadowOffset: { width: 0, height: 12 },
      elevation: 4,
      overflow: 'hidden',
    },
    heroLabel: {
      color: theme.primary,
      fontSize: moderateScale(12),
      fontWeight: '900',
      letterSpacing: 1.4,
      textTransform: 'uppercase',
    },
    heroTitle: {
      color: theme.text,
      marginTop: scale(8),
      fontSize: moderateScale(23),
      lineHeight: moderateScale(31),
      fontWeight: '900',
    },
    heroSubtitle: {
      color: theme.muted,
      marginTop: scale(6),
      fontSize: moderateScale(13),
      lineHeight: moderateScale(19),
    },
    heroStatsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginTop: scale(14),
      gap: scale(10),
    },
    statCard: {
      flexBasis: (SCREEN_WIDTH - scale(52)) / 2,
      flexGrow: 1,
      padding: scale(14),
      borderRadius: scale(20),
      backgroundColor: theme.surfaceAlt,
      borderWidth: 1,
      borderColor: theme.border,
    },
    statValue: { color: theme.text, fontSize: moderateScale(21), fontWeight: '900' },
    statLabel: {
      color: theme.muted,
      marginTop: scale(4),
      fontSize: moderateScale(12),
      fontWeight: '700',
    },
    segmented: {
      flexDirection: 'row',
      gap: scale(8),
      paddingHorizontal: scale(16),
      paddingBottom: scale(10),
    },
    segmentedBtn: {
      flex: 1,
      minHeight: scale(48),
      borderRadius: scale(18),
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surface,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: scale(8),
      paddingHorizontal: scale(10),
    },
    segmentedBtnActive: { backgroundColor: theme.primary, borderColor: theme.primary },
    segmentedText: { color: theme.text, fontSize: moderateScale(13), fontWeight: '800' },
    segmentedTextActive: { color: theme.primaryText },
    body: { flex: 1, minHeight: 0 },

    authWrap: {
      flex: 1,
      backgroundColor: theme.background,
      justifyContent: 'center',
      padding: scale(16),
    },
    authScroll: { flexGrow: 1, justifyContent: 'center', paddingVertical: scale(18) },
    authCard: {
      borderRadius: scale(30),
      padding: scale(18),
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
      shadowColor: theme.shadow,
      shadowOpacity: 0.25,
      shadowRadius: 26,
      shadowOffset: { width: 0, height: 16 },
      elevation: 5,
      overflow: 'hidden',
    },
    authGlow: {
      position: 'absolute',
      left: -40,
      top: -40,
      width: 160,
      height: 160,
      borderRadius: 160,
      backgroundColor: 'rgba(89,216,255,0.12)',
    },
    authBadge: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 10,
    },
    authTitle: {
      color: theme.text,
      textAlign: 'center',
      fontSize: moderateScale(30),
      fontWeight: '900',
      letterSpacing: 0.7,
    },
    authSubtitle: {
      color: theme.muted,
      textAlign: 'center',
      marginTop: scale(8),
      fontSize: moderateScale(13),
      lineHeight: moderateScale(19),
    },
    authTabs: {
      flexDirection: 'row',
      gap: scale(8),
      marginTop: scale(16),
    },
    authTab: {
      flex: 1,
      minHeight: scale(42),
      borderRadius: scale(16),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.surfaceAlt,
      borderWidth: 1,
      borderColor: theme.border,
    },
    authTabActive: { backgroundColor: theme.primary, borderColor: theme.primary },
    authTabText: { color: theme.text, fontSize: moderateScale(13), fontWeight: '800' },
    authTabTextActive: { color: theme.primaryText },
    authField: {
      minHeight: scale(52),
      borderRadius: scale(18),
      paddingHorizontal: scale(14),
      backgroundColor: theme.surfaceAlt,
      borderWidth: 1,
      borderColor: theme.border,
      flexDirection: 'row',
      alignItems: 'center',
      gap: scale(10),
    },
    authInput: {
      flex: 1,
      minHeight: scale(52),
      color: theme.text,
      fontSize: moderateScale(15),
      paddingVertical: 0,
    },
    authPrimaryBtn: {
      minHeight: scale(54),
      borderRadius: scale(18),
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: scale(10),
      marginTop: scale(14),
      paddingHorizontal: scale(14),
      shadowColor: theme.primary,
      shadowOpacity: 0.35,
      shadowRadius: 16,
      shadowOffset: { width: 0, height: 8 },
      elevation: 4,
    },
    authPrimaryBtnText: { color: theme.primaryText, fontSize: moderateScale(15), fontWeight: '900' },
    authSecondaryTextBtn: { marginTop: scale(12), alignItems: 'center', justifyContent: 'center' },
    authSecondaryText: { color: theme.muted, fontSize: moderateScale(13), textAlign: 'center' },
    authSecondaryStrong: { color: theme.text, fontWeight: '900' },
    authHintBox: {
      marginTop: scale(14),
      borderRadius: scale(20),
      padding: scale(14),
      backgroundColor: 'rgba(89,216,255,0.08)',
      borderWidth: 1,
      borderColor: 'rgba(89,216,255,0.18)',
    },
    authHintTitle: { color: theme.text, fontSize: moderateScale(13), fontWeight: '900', letterSpacing: 0.3 },
    authHintText: {
      color: theme.muted,
      marginTop: scale(6),
      fontSize: moderateScale(12),
      lineHeight: moderateScale(18),
    },
    authVisitorBtn: {
      minHeight: scale(50),
      borderRadius: scale(18),
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: scale(10),
      marginTop: scale(14),
      backgroundColor: 'rgba(89,216,255,0.14)',
      borderWidth: 1,
      borderColor: 'rgba(89,216,255,0.22)',
    },
    authVisitorBtnText: { color: theme.text, fontSize: moderateScale(14), fontWeight: '900' },
    authInlineLabel: {
      color: theme.muted,
      fontSize: moderateScale(12),
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 0.8,
      marginTop: scale(12),
      marginBottom: scale(4),
    },
    authPulseRing: {
      position: 'absolute',
      borderWidth: 1,
      borderColor: 'rgba(89,216,255,0.25)',
      borderRadius: 999,
    },
    authPulseCenter: {
      width: scale(36),
      height: scale(36),
      borderRadius: 999,
      backgroundColor: theme.primary,
      shadowColor: theme.primary,
      shadowOpacity: 0.4,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 0 },
      elevation: 5,
    },
    authPulseScan: {
      position: 'absolute',
      width: scale(70),
      height: scale(2),
      backgroundColor: 'rgba(89,216,255,0.85)',
      borderRadius: 999,
      transform: [{ rotate: '18deg' }],
    },

    menuOverlay: { flex: 1, backgroundColor: 'rgba(2,6,23,0.66)', flexDirection: 'row' },
    menuBackdrop: { flex: 1 },
    menuSheet: {
      width: '70%',
      height: '77%',
      marginTop: 30,
      maxWidth: 320,
      backgroundColor: theme.surface,
      borderRightWidth: 1,
      borderRightColor: theme.border,
      borderRadius: 30,
      paddingTop: scale(16),
      paddingHorizontal: scale(16),
      shadowColor: theme.shadow,
      shadowOpacity: 0.25,
      shadowRadius: 24,
      shadowOffset: { width: 4, height: 0 },
      elevation: 10,
    },
    menuHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: scale(10),
      paddingBottom: scale(12),
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
      marginBottom: scale(12),
    },
    menuTitle: { color: theme.text, fontSize: moderateScale(19), fontWeight: '900', letterSpacing: 0.2 },
    menuSubtitle: {
      color: theme.muted,
      marginTop: scale(3),
      fontSize: moderateScale(12),
      lineHeight: moderateScale(17),
    },
    menuIdentityText: { color: theme.primaryText, fontSize: moderateScale(16), fontWeight: '900' },
    menuBlock: { gap: scale(8), paddingBottom: scale(18) },
    menuAction: {
      minHeight: scale(50),
      borderRadius: scale(16),
      paddingHorizontal: scale(14),
      backgroundColor: theme.surfaceAlt,
      borderWidth: 1,
      borderColor: theme.border,
      flexDirection: 'row',
      alignItems: 'center',
      gap: scale(10),
    },
    menuActionText: { color: theme.text, flex: 1, fontSize: moderateScale(13), fontWeight: '800' },
    menuDangerText: { color: theme.danger },

    overlayModal: { flex: 1, backgroundColor: theme.background },
    modalHeader: {
      paddingTop: scale(12),
      paddingHorizontal: scale(16),
      paddingBottom: scale(12),
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: scale(12),
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
      backgroundColor: theme.background,
    },
    modalTitle: { color: theme.text, fontSize: moderateScale(24), fontWeight: '900', letterSpacing: 0.3 },
    modalSubtitle: {
      color: theme.muted,
      marginTop: scale(4),
      fontSize: moderateScale(12),
      lineHeight: moderateScale(18),
    },
    contentPadding: { paddingHorizontal: scale(16), paddingTop: scale(14) },

    filterRow: { flexDirection: 'row', flexWrap: 'wrap', gap: scale(8) },
    chip: {
      minHeight: scale(34),
      paddingHorizontal: scale(12),
      paddingVertical: scale(8),
      borderRadius: scale(999),
      backgroundColor: theme.surfaceAlt,
      borderWidth: 1,
      borderColor: theme.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    chipActive: { backgroundColor: theme.primary, borderColor: theme.primary },
    chipText: { color: theme.text, fontSize: moderateScale(12), fontWeight: '800' },
    chipTextActive: { color: theme.primaryText },

    sectionHeader: { marginTop: scale(-2), marginBottom: scale(10) },

    sectionHeaderTitle: {
      color: theme.text,
      fontSize: moderateScale(22),
      fontWeight: '900' },

    sectionHeaderSubtitle: {
      color: theme.muted,
      marginTop: scale(4),
      fontSize: moderateScale(12),
      lineHeight: scale(17),
    },

    card: {
      borderRadius: scale(24),
      padding: scale(14),
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
      marginBottom: scale(12),
    },
    cardTop: { flexDirection: 'row', alignItems: 'flex-start', gap: scale(12) },
    stationName: {
      color: theme.text,
      fontSize: moderateScale(17),
      fontWeight: '900',
      lineHeight: moderateScale(22),
    },
    timeText: {
      color: theme.muted,
      marginTop: scale(4),
      fontSize: moderateScale(12),
      fontWeight: '700',
    },
    scorePill: {
      borderRadius: scale(999),
      minHeight: scale(30),
      paddingHorizontal: scale(12),
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: theme.surfaceAlt,
      borderWidth: 1,
      borderColor: theme.border,
    },
    scoreText: {
      color: theme.text,
      fontSize: moderateScale(12),
      fontWeight: '900',
      letterSpacing: 0.4,
    },
    noteText: {
      color: theme.text,
      fontSize: moderateScale(14),
      lineHeight: moderateScale(21),
      marginTop: scale(10),
    },
    divider: { height: 1, backgroundColor: theme.border, marginVertical: scale(14) },
    voteRow: { marginTop: scale(12), flexDirection: 'row', alignItems: 'center', gap: scale(10) },
    voteBtn: {
      minHeight: scale(40),
      paddingHorizontal: scale(12),
      borderRadius: scale(14),
      backgroundColor: theme.surfaceAlt,
      borderWidth: 1,
      borderColor: theme.border,
      flexDirection: 'row',
      alignItems: 'center',
      gap: scale(6),
    },
    voteValue: { color: theme.text, fontSize: moderateScale(13), fontWeight: '900' },
    deleteBtn: {
      minWidth: scale(40),
      minHeight: scale(40),
      paddingHorizontal: scale(12),
      borderRadius: scale(14),
      backgroundColor: 'rgba(255,48,48,0.12)',
      borderWidth: 1,
      borderColor: 'rgba(255,48,48,0.18)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    feedPhotoWrap: {
      marginTop: scale(12),
      borderRadius: scale(20),
      overflow: 'hidden',
      backgroundColor: theme.surfaceAlt,
      borderWidth: 1,
      borderColor: theme.border,
    },
    feedPhoto: { width: '100%', height: scale(200) },
    feedPhotoCaption: {
      color: theme.muted,
      paddingHorizontal: scale(12),
      paddingVertical: scale(10),
      fontSize: moderateScale(12),
      fontWeight: '700',
    },

    composerWrap: { paddingHorizontal: scale(16), paddingTop: scale(12) },
    composerCard: {
      borderRadius: scale(26),
      padding: scale(16),
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
      marginBottom: scale(14),
    },
    helperCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: scale(10),
      borderRadius: scale(18),
      backgroundColor: 'rgba(89,216,255,0.08)',
      borderWidth: 1,
      borderColor: 'rgba(89,216,255,0.18)',
      padding: scale(12),
      marginTop: scale(12),
    },
    helperTitle: { color: theme.text, fontSize: moderateScale(13), fontWeight: '900' },
    helperText: {
      color: theme.muted,
      marginTop: scale(4),
      fontSize: moderateScale(10),
      lineHeight: scale(17),
    },
    stationCountBadge: {
      alignSelf: 'flex-start',
      color: theme.text,
      fontSize: moderateScale(12),
      fontWeight: '900',
      marginTop: scale(10),
      paddingHorizontal: scale(10),
      paddingVertical: scale(6),
      borderRadius: scale(999),
      backgroundColor: theme.surfaceAlt,
      borderWidth: 1,
      borderColor: theme.border,
    },
    stationRow: {
      borderRadius: scale(18),
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
      padding: scale(14),
      marginTop: scale(10),
    },
    stationRowText: { color: theme.text, fontSize: moderateScale(14), fontWeight: '900' },
    stationRowSubtext: { color: theme.muted, marginTop: scale(4), fontSize: moderateScale(12) },
    emptyState: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: scale(28),
      paddingHorizontal: scale(20),
    },
    emptyTitle: {
      color: theme.text,
      marginTop: scale(10),
      fontSize: moderateScale(18),
      fontWeight: '900',
      textAlign: 'center',
    },
    emptySubtitle: {
      color: theme.muted,
      marginTop: scale(6),
      fontSize: moderateScale(13),
      textAlign: 'center',
      lineHeight: scale(19),
    },

    statusChoiceRow: { flexDirection: 'row', gap: scale(10), marginTop: scale(10) },
    statusChoice: {
      flex: 1,
      minHeight: scale(50),
      borderRadius: scale(18),
      borderWidth: 1,
      borderColor: theme.border,
      backgroundColor: theme.surfaceAlt,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: scale(10),
    },
    statusChoiceActiveSeen: {
      backgroundColor: 'rgba(74,222,128,0.14)',
      borderColor: 'rgba(74,222,128,0.26)',
    },
    statusChoiceActiveClear: {
      backgroundColor: 'rgba(255,92,92,0.14)',
      borderColor: 'rgba(255,92,92,0.28)',
    },
    statusChoiceText: { color: theme.text, fontSize: moderateScale(13), fontWeight: '900' },
    statusChoiceTextActive: { color: theme.text },

    reportSection: {
      marginTop: scale(14),
      borderRadius: scale(24),
      padding: scale(16),
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
    },
    reportHeroCard: {
      borderRadius: scale(26),
      padding: scale(16),
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
    },
    reportHeroTitle: { color: theme.text, fontSize: moderateScale(20), fontWeight: '900' },
    reportHeroSubtitle: {
      color: theme.muted,
      marginTop: scale(6),
      fontSize: moderateScale(13),
      lineHeight: moderateScale(19),
    },
    reportFieldLabel: {
      color: theme.text,
      fontSize: moderateScale(13),
      fontWeight: '900',
      marginTop: scale(1),
      marginBottom: scale(2),
    },
    noteInput: {
      minHeight: scale(96),
      borderRadius: scale(18),
      paddingHorizontal: scale(14),
      paddingVertical: scale(12),
      backgroundColor: theme.surfaceAlt,
      borderWidth: 1,
      borderColor: theme.border,
      color: theme.text,
      fontSize: moderateScale(14),
      lineHeight: moderateScale(20),
      textAlignVertical: 'top',
    },
    reportImageCard: {
      borderRadius: scale(22),
      overflow: 'hidden',
      backgroundColor: theme.surfaceAlt,
      borderWidth: 1,
      borderColor: theme.border,
      marginTop: scale(10),
    },
    reportImagePreview: { width: '100%', height: scale(220), backgroundColor: theme.surfaceAlt },
    reportImageActions: {
      flexDirection: 'row',
      gap: scale(10),
      padding: scale(12),
      flexWrap: 'wrap',
    },
    reportImageAction: {
      minHeight: scale(40),
      paddingHorizontal: scale(12),
      borderRadius: scale(14),
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    reportImageActionText: { color: theme.text, fontSize: moderateScale(12), fontWeight: '900' },
    reportHintBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: scale(8),
      marginTop: scale(12),
      padding: scale(12),
      borderRadius: scale(18),
      backgroundColor: 'rgba(255,212,74,0.10)',
      borderWidth: 1,
      borderColor: 'rgba(255,212,74,0.20)',
    },
    reportHintText: {
      color: theme.muted,
      fontSize: moderateScale(10),
      lineHeight: moderateScale(18),
    },
    reportPrimaryBtn: {
      minHeight: scale(58),
      borderRadius: scale(20),
      marginTop: scale(16),
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: theme.primary,
      shadowOpacity: 0.38,
      shadowRadius: 18,
      shadowOffset: { width: 0, height: 10 },
      elevation: 5,
    },
    reportPrimaryBtnText: {
      color: theme.primaryText,
      fontSize: moderateScale(16),
      fontWeight: '900',
      letterSpacing: 0.5,
    },

    talkShell: { flex: 1, backgroundColor: theme.background },
    talkHeader: {
      paddingHorizontal: scale(16),
      paddingTop: scale(12),
      paddingBottom: scale(10),
      borderBottomWidth: 1,
      borderBottomColor: theme.border,
      backgroundColor: theme.background,
    },
    talkHeaderTitle: { color: theme.text, fontSize: moderateScale(24), fontWeight: '900' },
    talkHeaderSubtitle: {
      color: theme.muted,
      marginTop: scale(4),
      fontSize: moderateScale(12),
      lineHeight: scale(17),
    },
    talkBanner: {
      marginTop: scale(12),
      borderRadius: scale(20),
      padding: scale(12),
      flexDirection: 'row',
      alignItems: 'center',
      gap: scale(10),
      backgroundColor: 'rgba(255,92,92,0.12)',
      borderWidth: 1,
      borderColor: 'rgba(255,92,92,0.22)',
    },
    talkBannerTitle: { color: theme.text, fontSize: moderateScale(13), fontWeight: '900' },
    talkBannerText: {
      color: theme.muted,
      marginTop: scale(4),
      fontSize: moderateScale(10),
      lineHeight: scale(17),
    },
    talkBubble: {
      width: '100%',
      borderRadius: scale(22),
      padding: scale(10),
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
    },
    talkBubbleMine: {
      backgroundColor: theme.surfaceAlt,
      borderColor: 'rgba(89,216,255,0.24)',
    },
    talkBubbleMeta: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: scale(10),
      marginBottom: scale(8),
      minWidth: 0,
    },
    talkBubbleName: { color: theme.text, fontSize: moderateScale(14), fontWeight: '900' },
    talkBubbleTime: {
      color: theme.muted,
      marginTop: scale(2),
      fontSize: moderateScale(11),
      fontWeight: '700',
    },
    talkBubbleText: {
      color: theme.text,
      fontSize: moderateScale(14),
      lineHeight: moderateScale(21),
    },
    talkAvatar: {
      width: scale(40),
      height: scale(40),
      borderRadius: scale(14),
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    talkAvatarText: { color: theme.primaryText, fontSize: moderateScale(13), fontWeight: '900' },
    talkComposer: {
      flexDirection: 'row',
      gap: scale(10),
      padding: scale(16),
      paddingTop: scale(12),
      backgroundColor: theme.background,
      borderTopWidth: 1,
      borderTopColor: theme.border,
    },
    talkComposerField: {
      flex: 1,
      minHeight: scale(54),
      borderRadius: scale(18),
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
      paddingHorizontal: scale(14),
      justifyContent: 'center',
    },
    talkComposerInput: {
      color: theme.text,
      fontSize: moderateScale(14),
      minHeight: scale(44),
      textAlignVertical: 'center',
    },
    talkSendBtn: {
      minWidth: scale(92),
      borderRadius: scale(18),
      backgroundColor: theme.primary,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: scale(14),
      minHeight: scale(54),
    },
    talkSendBtnDisabled: {
      backgroundColor: theme.surfaceAlt,
      borderWidth: 1,
      borderColor: theme.border,
    },
    talkSendBtnText: { color: theme.primaryText, fontSize: moderateScale(14), fontWeight: '900' },
    talkEmptyWrap: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: scale(30),
      paddingHorizontal: scale(20),
    },
    talkEmptyTitle: {
      color: theme.text,
      marginTop: scale(10),
      fontSize: moderateScale(18),
      fontWeight: '900',
      textAlign: 'center',
    },
    talkEmptySubtitle: {
      color: theme.muted,
      marginTop: scale(6),
      fontSize: moderateScale(13),
      lineHeight: scale(19),
      textAlign: 'center',
    },

    adminCard: {
      borderRadius: scale(24),
      padding: scale(16),
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
      marginBottom: scale(12),
    },
    adminGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: scale(10),
    },
    adminMetricCard: {
      flexBasis: (SCREEN_WIDTH - scale(52)) / 2,
      flexGrow: 1,
      borderRadius: scale(20),
      padding: scale(14),
      backgroundColor: theme.surfaceAlt,
      borderWidth: 1,
      borderColor: theme.border,
    },
    adminMetricValue: { color: theme.text, fontSize: moderateScale(22), fontWeight: '900' },
    adminMetricLabel: {
      color: theme.muted,
      marginTop: scale(4),
      fontSize: moderateScale(12),
      fontWeight: '700',
    },
    adminSectionTitle: { color: theme.text, fontSize: moderateScale(18), fontWeight: '900' },
    adminSectionSubtitle: {
      color: theme.muted,
      marginTop: scale(4),
      fontSize: moderateScale(12),
      lineHeight: scale(17),
    },
    adminEntryCard: {
      borderRadius: scale(20),
      padding: scale(14),
      backgroundColor: theme.surfaceAlt,
      borderWidth: 1,
      borderColor: theme.border,
      marginTop: scale(10),
    },
    adminEntryTagRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: scale(8),
      marginTop: scale(10),
    },
    adminEntryTag: {
      minHeight: scale(30),
      paddingHorizontal: scale(10),
      borderRadius: scale(999),
      backgroundColor: theme.surface,
      borderWidth: 1,
      borderColor: theme.border,
      alignItems: 'center',
      justifyContent: 'center',
    },
    adminEntryTitle: { color: theme.text, fontSize: moderateScale(15), fontWeight: '900' },
    adminEntryTime: {
      color: theme.muted,
      marginTop: scale(4),
      fontSize: moderateScale(11),
      fontWeight: '700',
    },
    adminEntryBody: {
      color: theme.text,
      marginTop: scale(8),
      fontSize: moderateScale(13),
      lineHeight: scale(19),
    },
    adminEmptyCard: {
      borderRadius: scale(20),
      padding: scale(14),
      backgroundColor: theme.surfaceAlt,
      borderWidth: 1,
      borderColor: theme.border,
      marginTop: scale(10),
      alignItems: 'center',
      justifyContent: 'center',
    },
    adminLockBadge: {
      width: scale(68),
      height: scale(68),
      borderRadius: scale(22),
      backgroundColor: 'rgba(255,92,92,0.14)',
      borderWidth: 1,
      borderColor: 'rgba(255,92,92,0.22)',
      alignItems: 'center',
      justifyContent: 'center',
      alignSelf: 'center',
      marginBottom: scale(10),
    },
    adminLockText: {
      color: theme.text,
      fontSize: moderateScale(12),
      fontWeight: '900',
      letterSpacing: 0.7,
      textTransform: 'uppercase',
    },
    radarWrap: {
      width: scale(132),
      height: scale(132),
      alignSelf: 'center',
      justifyContent: 'center',
      alignItems: 'center',
      position: 'relative',
      marginBottom: scale(12),
    },
  });
}
